// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/clinton-maryland-replacement-windows-and-door-company-near-me": {
    params: {};
  };
  "/clinton-maryland-roofing-siding-gutter-contractors-near-me": {
    params: {};
  };
  "/roofing-siding-contractors-near-you-in-crofton-md": {
    params: {};
  };
  "/roofing-siding-contractors-near-you-silver-spring": {
    params: {};
  };
  "/service/wilmington-nc-roofing-company-near-you": {
    params: {};
  };
  "/roofing-siding-contractors-near-you-laurel": {
    params: {};
  };
  "/farmlands/integrated-pest-management": {
    params: {};
  };
  "/deck-and-patios/flagstone-patios": {
    params: {};
  };
  "/deck-and-patios/ipe-deck-builder": {
    params: {};
  };
  "/commercial-roof-cost-calculator": {
    params: {};
  };
  "/deck-and-patios/rooftop-deck": {
    params: {};
  };
  "/roofing/commercial-roofing": {
    params: {};
  };
  "/forestry-mulching-value-add": {
    params: {};
  };
  "/james-hardie-colors/:slug": {
    params: {
      "slug": string;
    };
  };
  "/locations/washington-dc": {
    params: {};
  };
  "/roofing/asphalt-roofing": {
    params: {};
  };
  "/locations/gaithersburg": {
    params: {};
  };
  "/roofing-cost-calculator": {
    params: {};
  };
  "/roofing/metal-roofing": {
    params: {};
  };
  "/timbertech-colors/:slug": {
    params: {
      "slug": string;
    };
  };
  "/upper-marlboro-maryland": {
    params: {};
  };
  "/land/family-farmland": {
    params: {};
  };
  "/roofing/flat-roofing": {
    params: {};
  };
  "/siding/james-hardie": {
    params: {};
  };
  "/forestry-mulching": {
    params: {};
  };
  "/locations/bowie": {
    params: {};
  };
  "/decks-and-patios": {
    params: {};
  };
  "/farmlands/land": {
    params: {};
  };
  "/home-trailer-qr": {
    params: {};
  };
  "/quote-requested": {
    params: {};
  };
  "/services/:slug": {
    params: {
      "slug": string;
    };
  };
  "/siding/vinyl": {
    params: {};
  };
  "/exterior-trim": {
    params: {};
  };
  "/service-areas": {
    params: {};
  };
  "/video-gallery": {
    params: {};
  };
  "/mapembedtest": {
    params: {};
  };
  "/testimonials": {
    params: {};
  };
  "/videos/:slug": {
    params: {
      "slug": string;
    };
  };
  "/sitemap.xml": {
    params: {};
  };
  "/style-guide": {
    params: {};
  };
  "/blog/:slug": {
    params: {
      "slug": string;
    };
  };
  "/chatwidget": {
    params: {};
  };
  "/financing": {
    params: {};
  };
  "/locations": {
    params: {};
  };
  "/lp/:slug": {
    params: {
      "slug": string;
    };
  };
  "/warranty": {
    params: {};
  };
  "/contact": {
    params: {};
  };
  "/gallery": {
    params: {};
  };
  "/gutters": {
    params: {};
  };
  "/roofing": {
    params: {};
  };
  "/windows": {
    params: {};
  };
  "/siding": {
    params: {};
  };
  "/about": {
    params: {};
  };
  "/doors": {
    params: {};
  };
  "/quote": {
    params: {};
  };
  "/blog": {
    params: {};
  };
  "/team": {
    params: {};
  };
  "/robots.txt": {
    params: {};
  };
  "/_image/*": {
    params: {
      "*": string;
    };
  };
  "/*": {
    params: {
      "*": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/clinton-maryland-replacement-windows-and-door-company-near-me" | "/clinton-maryland-roofing-siding-gutter-contractors-near-me" | "/roofing-siding-contractors-near-you-in-crofton-md" | "/roofing-siding-contractors-near-you-silver-spring" | "/service/wilmington-nc-roofing-company-near-you" | "/roofing-siding-contractors-near-you-laurel" | "/farmlands/integrated-pest-management" | "/deck-and-patios/flagstone-patios" | "/deck-and-patios/ipe-deck-builder" | "/commercial-roof-cost-calculator" | "/deck-and-patios/rooftop-deck" | "/roofing/commercial-roofing" | "/forestry-mulching-value-add" | "/james-hardie-colors/:slug" | "/locations/washington-dc" | "/roofing/asphalt-roofing" | "/locations/gaithersburg" | "/roofing-cost-calculator" | "/roofing/metal-roofing" | "/timbertech-colors/:slug" | "/upper-marlboro-maryland" | "/land/family-farmland" | "/roofing/flat-roofing" | "/siding/james-hardie" | "/forestry-mulching" | "/locations/bowie" | "/decks-and-patios" | "/farmlands/land" | "/home-trailer-qr" | "/quote-requested" | "/services/:slug" | "/siding/vinyl" | "/exterior-trim" | "/service-areas" | "/video-gallery" | "/mapembedtest" | "/testimonials" | "/videos/:slug" | "/sitemap.xml" | "/style-guide" | "/blog/:slug" | "/chatwidget" | "/financing" | "/locations" | "/lp/:slug" | "/warranty" | "/contact" | "/gallery" | "/gutters" | "/roofing" | "/windows" | "/siding" | "/about" | "/doors" | "/quote" | "/blog" | "/team" | "/robots.txt" | "/_image/*" | "/*";
  };
  "routes/[clinton-maryland-replacement-windows-and-door-company-near-me]._index.tsx": {
    id: "routes/[clinton-maryland-replacement-windows-and-door-company-near-me]._index";
    page: "/clinton-maryland-replacement-windows-and-door-company-near-me";
  };
  "routes/[clinton-maryland-roofing-siding-gutter-contractors-near-me]._index.tsx": {
    id: "routes/[clinton-maryland-roofing-siding-gutter-contractors-near-me]._index";
    page: "/clinton-maryland-roofing-siding-gutter-contractors-near-me";
  };
  "routes/[roofing-siding-contractors-near-you-in-crofton-md]._index.tsx": {
    id: "routes/[roofing-siding-contractors-near-you-in-crofton-md]._index";
    page: "/roofing-siding-contractors-near-you-in-crofton-md";
  };
  "routes/[roofing-siding-contractors-near-you-silver-spring]._index.tsx": {
    id: "routes/[roofing-siding-contractors-near-you-silver-spring]._index";
    page: "/roofing-siding-contractors-near-you-silver-spring";
  };
  "routes/[service].[wilmington-nc-roofing-company-near-you]._index.tsx": {
    id: "routes/[service].[wilmington-nc-roofing-company-near-you]._index";
    page: "/service/wilmington-nc-roofing-company-near-you";
  };
  "routes/[roofing-siding-contractors-near-you-laurel]._index.tsx": {
    id: "routes/[roofing-siding-contractors-near-you-laurel]._index";
    page: "/roofing-siding-contractors-near-you-laurel";
  };
  "routes/[farmlands].[integrated-pest-management]._index.tsx": {
    id: "routes/[farmlands].[integrated-pest-management]._index";
    page: "/farmlands/integrated-pest-management";
  };
  "routes/[deck-and-patios].[flagstone-patios]._index.tsx": {
    id: "routes/[deck-and-patios].[flagstone-patios]._index";
    page: "/deck-and-patios/flagstone-patios";
  };
  "routes/[deck-and-patios].[ipe-deck-builder]._index.tsx": {
    id: "routes/[deck-and-patios].[ipe-deck-builder]._index";
    page: "/deck-and-patios/ipe-deck-builder";
  };
  "routes/[commercial-roof-cost-calculator]._index.tsx": {
    id: "routes/[commercial-roof-cost-calculator]._index";
    page: "/commercial-roof-cost-calculator";
  };
  "routes/[deck-and-patios].[rooftop-deck]._index.tsx": {
    id: "routes/[deck-and-patios].[rooftop-deck]._index";
    page: "/deck-and-patios/rooftop-deck";
  };
  "routes/[roofing].[commercial-roofing]._index.tsx": {
    id: "routes/[roofing].[commercial-roofing]._index";
    page: "/roofing/commercial-roofing";
  };
  "routes/[forestry-mulching-value-add]._index.tsx": {
    id: "routes/[forestry-mulching-value-add]._index";
    page: "/forestry-mulching-value-add";
  };
  "routes/[james-hardie-colors].$slug._index.tsx": {
    id: "routes/[james-hardie-colors].$slug._index";
    page: "/james-hardie-colors/:slug";
  };
  "routes/[locations].[washington-dc]._index.tsx": {
    id: "routes/[locations].[washington-dc]._index";
    page: "/locations/washington-dc";
  };
  "routes/[roofing].[asphalt-roofing]._index.tsx": {
    id: "routes/[roofing].[asphalt-roofing]._index";
    page: "/roofing/asphalt-roofing";
  };
  "routes/[locations].[gaithersburg]._index.tsx": {
    id: "routes/[locations].[gaithersburg]._index";
    page: "/locations/gaithersburg";
  };
  "routes/[roofing-cost-calculator]._index.tsx": {
    id: "routes/[roofing-cost-calculator]._index";
    page: "/roofing-cost-calculator";
  };
  "routes/[roofing].[metal-roofing]._index.tsx": {
    id: "routes/[roofing].[metal-roofing]._index";
    page: "/roofing/metal-roofing";
  };
  "routes/[timbertech-colors].$slug._index.tsx": {
    id: "routes/[timbertech-colors].$slug._index";
    page: "/timbertech-colors/:slug";
  };
  "routes/[upper-marlboro-maryland]._index.tsx": {
    id: "routes/[upper-marlboro-maryland]._index";
    page: "/upper-marlboro-maryland";
  };
  "routes/[land].[family-farmland]._index.tsx": {
    id: "routes/[land].[family-farmland]._index";
    page: "/land/family-farmland";
  };
  "routes/[roofing].[flat-roofing]._index.tsx": {
    id: "routes/[roofing].[flat-roofing]._index";
    page: "/roofing/flat-roofing";
  };
  "routes/[siding].[james-hardie]._index.tsx": {
    id: "routes/[siding].[james-hardie]._index";
    page: "/siding/james-hardie";
  };
  "routes/[forestry-mulching]._index.tsx": {
    id: "routes/[forestry-mulching]._index";
    page: "/forestry-mulching";
  };
  "routes/[locations].[bowie]._index.tsx": {
    id: "routes/[locations].[bowie]._index";
    page: "/locations/bowie";
  };
  "routes/[decks-and-patios]._index.tsx": {
    id: "routes/[decks-and-patios]._index";
    page: "/decks-and-patios";
  };
  "routes/[farmlands].[land]._index.tsx": {
    id: "routes/[farmlands].[land]._index";
    page: "/farmlands/land";
  };
  "routes/[home-trailer-qr]._index.tsx": {
    id: "routes/[home-trailer-qr]._index";
    page: "/home-trailer-qr";
  };
  "routes/[quote-requested]._index.tsx": {
    id: "routes/[quote-requested]._index";
    page: "/quote-requested";
  };
  "routes/[services].$slug._index.tsx": {
    id: "routes/[services].$slug._index";
    page: "/services/:slug";
  };
  "routes/[siding].[vinyl]._index.tsx": {
    id: "routes/[siding].[vinyl]._index";
    page: "/siding/vinyl";
  };
  "routes/[exterior-trim]._index.tsx": {
    id: "routes/[exterior-trim]._index";
    page: "/exterior-trim";
  };
  "routes/[service-areas]._index.tsx": {
    id: "routes/[service-areas]._index";
    page: "/service-areas";
  };
  "routes/[video-gallery]._index.tsx": {
    id: "routes/[video-gallery]._index";
    page: "/video-gallery";
  };
  "routes/[mapembedtest]._index.tsx": {
    id: "routes/[mapembedtest]._index";
    page: "/mapembedtest";
  };
  "routes/[testimonials]._index.tsx": {
    id: "routes/[testimonials]._index";
    page: "/testimonials";
  };
  "routes/[videos].$slug._index.tsx": {
    id: "routes/[videos].$slug._index";
    page: "/videos/:slug";
  };
  "routes/[sitemap.xml]._index.tsx": {
    id: "routes/[sitemap.xml]._index";
    page: "/sitemap.xml";
  };
  "routes/[style-guide]._index.tsx": {
    id: "routes/[style-guide]._index";
    page: "/style-guide";
  };
  "routes/[blog].$slug._index.tsx": {
    id: "routes/[blog].$slug._index";
    page: "/blog/:slug";
  };
  "routes/[chatwidget]._index.tsx": {
    id: "routes/[chatwidget]._index";
    page: "/chatwidget";
  };
  "routes/[financing]._index.tsx": {
    id: "routes/[financing]._index";
    page: "/financing";
  };
  "routes/[locations]._index.tsx": {
    id: "routes/[locations]._index";
    page: "/locations";
  };
  "routes/[lp].$slug._index.tsx": {
    id: "routes/[lp].$slug._index";
    page: "/lp/:slug";
  };
  "routes/[warranty]._index.tsx": {
    id: "routes/[warranty]._index";
    page: "/warranty";
  };
  "routes/[contact]._index.tsx": {
    id: "routes/[contact]._index";
    page: "/contact";
  };
  "routes/[gallery]._index.tsx": {
    id: "routes/[gallery]._index";
    page: "/gallery";
  };
  "routes/[gutters]._index.tsx": {
    id: "routes/[gutters]._index";
    page: "/gutters";
  };
  "routes/[roofing]._index.tsx": {
    id: "routes/[roofing]._index";
    page: "/roofing";
  };
  "routes/[windows]._index.tsx": {
    id: "routes/[windows]._index";
    page: "/windows";
  };
  "routes/[siding]._index.tsx": {
    id: "routes/[siding]._index";
    page: "/siding";
  };
  "routes/[about]._index.tsx": {
    id: "routes/[about]._index";
    page: "/about";
  };
  "routes/[doors]._index.tsx": {
    id: "routes/[doors]._index";
    page: "/doors";
  };
  "routes/[quote]._index.tsx": {
    id: "routes/[quote]._index";
    page: "/quote";
  };
  "routes/[blog]._index.tsx": {
    id: "routes/[blog]._index";
    page: "/blog";
  };
  "routes/[team]._index.tsx": {
    id: "routes/[team]._index";
    page: "/team";
  };
  "routes/[robots.txt].tsx": {
    id: "routes/[robots.txt]";
    page: "/robots.txt";
  };
  "routes/[_image].$.ts": {
    id: "routes/[_image].$";
    page: "/_image/*";
  };
  "routes/_index.tsx": {
    id: "routes/_index";
    page: "/";
  };
  "routes/$.tsx": {
    id: "routes/$";
    page: "/*";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/[clinton-maryland-replacement-windows-and-door-company-near-me]._index": typeof import("./app/routes/[clinton-maryland-replacement-windows-and-door-company-near-me]._index.tsx");
  "routes/[clinton-maryland-roofing-siding-gutter-contractors-near-me]._index": typeof import("./app/routes/[clinton-maryland-roofing-siding-gutter-contractors-near-me]._index.tsx");
  "routes/[roofing-siding-contractors-near-you-in-crofton-md]._index": typeof import("./app/routes/[roofing-siding-contractors-near-you-in-crofton-md]._index.tsx");
  "routes/[roofing-siding-contractors-near-you-silver-spring]._index": typeof import("./app/routes/[roofing-siding-contractors-near-you-silver-spring]._index.tsx");
  "routes/[service].[wilmington-nc-roofing-company-near-you]._index": typeof import("./app/routes/[service].[wilmington-nc-roofing-company-near-you]._index.tsx");
  "routes/[roofing-siding-contractors-near-you-laurel]._index": typeof import("./app/routes/[roofing-siding-contractors-near-you-laurel]._index.tsx");
  "routes/[farmlands].[integrated-pest-management]._index": typeof import("./app/routes/[farmlands].[integrated-pest-management]._index.tsx");
  "routes/[deck-and-patios].[flagstone-patios]._index": typeof import("./app/routes/[deck-and-patios].[flagstone-patios]._index.tsx");
  "routes/[deck-and-patios].[ipe-deck-builder]._index": typeof import("./app/routes/[deck-and-patios].[ipe-deck-builder]._index.tsx");
  "routes/[commercial-roof-cost-calculator]._index": typeof import("./app/routes/[commercial-roof-cost-calculator]._index.tsx");
  "routes/[deck-and-patios].[rooftop-deck]._index": typeof import("./app/routes/[deck-and-patios].[rooftop-deck]._index.tsx");
  "routes/[roofing].[commercial-roofing]._index": typeof import("./app/routes/[roofing].[commercial-roofing]._index.tsx");
  "routes/[forestry-mulching-value-add]._index": typeof import("./app/routes/[forestry-mulching-value-add]._index.tsx");
  "routes/[james-hardie-colors].$slug._index": typeof import("./app/routes/[james-hardie-colors].$slug._index.tsx");
  "routes/[locations].[washington-dc]._index": typeof import("./app/routes/[locations].[washington-dc]._index.tsx");
  "routes/[roofing].[asphalt-roofing]._index": typeof import("./app/routes/[roofing].[asphalt-roofing]._index.tsx");
  "routes/[locations].[gaithersburg]._index": typeof import("./app/routes/[locations].[gaithersburg]._index.tsx");
  "routes/[roofing-cost-calculator]._index": typeof import("./app/routes/[roofing-cost-calculator]._index.tsx");
  "routes/[roofing].[metal-roofing]._index": typeof import("./app/routes/[roofing].[metal-roofing]._index.tsx");
  "routes/[timbertech-colors].$slug._index": typeof import("./app/routes/[timbertech-colors].$slug._index.tsx");
  "routes/[upper-marlboro-maryland]._index": typeof import("./app/routes/[upper-marlboro-maryland]._index.tsx");
  "routes/[land].[family-farmland]._index": typeof import("./app/routes/[land].[family-farmland]._index.tsx");
  "routes/[roofing].[flat-roofing]._index": typeof import("./app/routes/[roofing].[flat-roofing]._index.tsx");
  "routes/[siding].[james-hardie]._index": typeof import("./app/routes/[siding].[james-hardie]._index.tsx");
  "routes/[forestry-mulching]._index": typeof import("./app/routes/[forestry-mulching]._index.tsx");
  "routes/[locations].[bowie]._index": typeof import("./app/routes/[locations].[bowie]._index.tsx");
  "routes/[decks-and-patios]._index": typeof import("./app/routes/[decks-and-patios]._index.tsx");
  "routes/[farmlands].[land]._index": typeof import("./app/routes/[farmlands].[land]._index.tsx");
  "routes/[home-trailer-qr]._index": typeof import("./app/routes/[home-trailer-qr]._index.tsx");
  "routes/[quote-requested]._index": typeof import("./app/routes/[quote-requested]._index.tsx");
  "routes/[services].$slug._index": typeof import("./app/routes/[services].$slug._index.tsx");
  "routes/[siding].[vinyl]._index": typeof import("./app/routes/[siding].[vinyl]._index.tsx");
  "routes/[exterior-trim]._index": typeof import("./app/routes/[exterior-trim]._index.tsx");
  "routes/[service-areas]._index": typeof import("./app/routes/[service-areas]._index.tsx");
  "routes/[video-gallery]._index": typeof import("./app/routes/[video-gallery]._index.tsx");
  "routes/[mapembedtest]._index": typeof import("./app/routes/[mapembedtest]._index.tsx");
  "routes/[testimonials]._index": typeof import("./app/routes/[testimonials]._index.tsx");
  "routes/[videos].$slug._index": typeof import("./app/routes/[videos].$slug._index.tsx");
  "routes/[sitemap.xml]._index": typeof import("./app/routes/[sitemap.xml]._index.tsx");
  "routes/[style-guide]._index": typeof import("./app/routes/[style-guide]._index.tsx");
  "routes/[blog].$slug._index": typeof import("./app/routes/[blog].$slug._index.tsx");
  "routes/[chatwidget]._index": typeof import("./app/routes/[chatwidget]._index.tsx");
  "routes/[financing]._index": typeof import("./app/routes/[financing]._index.tsx");
  "routes/[locations]._index": typeof import("./app/routes/[locations]._index.tsx");
  "routes/[lp].$slug._index": typeof import("./app/routes/[lp].$slug._index.tsx");
  "routes/[warranty]._index": typeof import("./app/routes/[warranty]._index.tsx");
  "routes/[contact]._index": typeof import("./app/routes/[contact]._index.tsx");
  "routes/[gallery]._index": typeof import("./app/routes/[gallery]._index.tsx");
  "routes/[gutters]._index": typeof import("./app/routes/[gutters]._index.tsx");
  "routes/[roofing]._index": typeof import("./app/routes/[roofing]._index.tsx");
  "routes/[windows]._index": typeof import("./app/routes/[windows]._index.tsx");
  "routes/[siding]._index": typeof import("./app/routes/[siding]._index.tsx");
  "routes/[about]._index": typeof import("./app/routes/[about]._index.tsx");
  "routes/[doors]._index": typeof import("./app/routes/[doors]._index.tsx");
  "routes/[quote]._index": typeof import("./app/routes/[quote]._index.tsx");
  "routes/[blog]._index": typeof import("./app/routes/[blog]._index.tsx");
  "routes/[team]._index": typeof import("./app/routes/[team]._index.tsx");
  "routes/[robots.txt]": typeof import("./app/routes/[robots.txt].tsx");
  "routes/[_image].$": typeof import("./app/routes/[_image].$.ts");
  "routes/_index": typeof import("./app/routes/_index.tsx");
  "routes/$": typeof import("./app/routes/$.tsx");
};